### ISSUE TITLE
Run by keywords

### ISSUE THREAD

**Issue by jczech** [mcellteam/nutmeg#3]
Currently, you can run tests by number, range, or the special "all" keyword. It might be nice to be able to run tests by specifying one of the "keywords" (e.g. releases, warning messages, error messages, regression, etc) in the json test description.

**Comment by haskelladdict** [comment]
Ha, this feature actually existed already using the -R flag (nutmeg -R <category>). Unfortunately it was broken previously but should now work as expected with commit 68966ad7).
